#!/bin/bash
nm-applet&
sleep 1 &
gnome-power-manager&
sleep 1 &
gkrellm &
sleep 1 &
xfce4-clipman &
sleep 1 &
Esetroot -m .icewm/labr.jpg &
gksu /usr/bin/gnome-keyring-daemon --start --components=pkcs11
#devilspie &
gnome-terminal --window-with-profile=DesktopConsole &
